version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.3
    working_directory: ~/pbxx
    steps:
      - checkout

      - restore_cache:
          keys:
            - ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "ruby-parameter-store.gemspec" }}
            - ruby-cache-{{ arch }}-{{ .Branch }}
            - ruby-cache

      - run:
          name: Download cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Bundle Install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - save_cache:
          key: ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "ruby-parameter-store.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress
            ./cc-test-reporter after-build -t simplecov --exit-code $?

      - store_test_results:
          path: test_results

      - run:
          name: Upload to Gemfury
          context: gem
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gem build ruby-parameter-store.gemspec
              curl --fail -F package=@ruby-parameter-store-0.0.2.gem https://$GEMFURY_PUSH_TOKEN@push.fury.io/promoboxx/
            fi

